### ISSUE TITLE
Aba do cardápio fecha ao clicar com mouse

### ISSUE THREAD

**Issue by campagnucci** [prefeiturasp/SME-PratoAberto-Frontend#1]
Quando um item de faixa etária é expandido, o cardápio do dia fica visível. Porém, um simples clique de mouse (por exemplo, se tentar selecionar texto para copiar) faz com que ele recolha novamente. Deveria ficar aberto até o usuário optar por recolher (clicando em cima daquela faixa etária novamente) ou opte por expandir outra faixa etária.

**Comment by raphaelbluteau** [comment]
Vou trabalhar nessa correção

**Comment by pamnovalli** [comment]
Issue Resolvida
