### ISSUE TITLE
Faixa etaria fora de ordem

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-Frontend#10]
O correto seria a ordenação ser da menor idade para a maior idade. O que não está acontecendo. Um exemplo do erro está contido na imagem.

![faixa etaria](https://user-images.githubusercontent.com/1562636/40631372-6b09a73a-62b2-11e8-816f-f33f18e9ce21.jpg)

**Comment by ronaiza-cardoso** [comment]
posso pegar essa

**Comment by ronaiza-cardoso** [comment]
fiz alguns testes navegando pelo site e a idade está ordenada, vc tem o caso específico onde ele aconteça?

**Comment by pamnovalli** [comment]
Issue fechada
