### ISSUE TITLE
Dockerizar a aplicação

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-Frontend#29]
A aplicação ainda não utiliza containers. Temos prefência por docker, utilizando docker-compose.

**Comment by marce1994** [comment]
Hello, i will try to do it :).

**Comment by marce1994** [comment]
Sorry about the time, i was working on it, and i run into a problem with my docker installation.

It will take more time.

Thanks!

**Comment by ludimila** [comment]
@marce1994 its ok

**Comment by marce1994** [comment]
I think its done 👍  it my first pull request since im in github :)

Thanks!
