### ISSUE TITLE
Eliminar código duplicado

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-Frontend#31]
Emininar código duplicado apontado pelo code climate.

https://codeclimate.com/github/prefeiturasp/SME-PratoAberto-Frontend/issues?category%5B%5D=duplication&status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=structure&engine_name%5B%5D=duplication

**Comment by lsfgrd** [comment]
Meu PR (#33) corrige uma das ocorrências de código duplicado (o do método camelize())!

**Comment by pamnovalli** [comment]
Issue Fechada
