### ISSUE TITLE
home__header sobrepondo com div inferior em desktop 

### ISSUE THREAD

**Issue by ludimila** [prefeiturasp/SME-PratoAberto-Frontend#7]
Dependendo tamanho da janela do browser, mexer tamanho da janela para reproduzir problema.

![home](https://user-images.githubusercontent.com/1562636/38198860-cfe06c9a-3664-11e8-9f4d-5a84dffe7377.png)

**Comment by leoassuncao** [comment]
Fiz um PR corrigindo essa issue.
Tive uma pequena dificuldade na hora do PR (por ser meu primeiro PR para um projeto) mas espero que tenha feito tudo corretamente.
